### PR TITLE
Add tzdata

### LINKED ISSUE #4: Setting timezone does not work
Setting the timezone by setting the TZ environment variable does not work. This could be resolved by installing tzdata into the image.

### PR DESCRIPTION
**Pull request by MarkJonas**
If tzdata is available in the image the local time can be used by setting
the TZ environment variable.

Resolves #4.

### CODE REVIEW

**Comment by b3vis** [comment]
Hi, 

Thanks for the PR, have you fully tested this? I personally havent had the need to set the timezone but if you can confirm it works as you expect I will merge the PR.

Kind regrards,
b3vis

**Comment by MarkJonas** [comment]
Yes, I tested it and it works to my satisfaction.

```
/ # date                                                                                                       
Tue Jan 23 21:26:11 CET 2018                                                                                   
/ # echo $TZ                                                                                                   
Europe/Berlin  
```

I also verified that cron now runs on local time.

**Comment by b3vis** [comment]
Thanks @MarkJonas I've merged your PR just now. the Docker Hub will pick this up and automatically build a new image.

**Comment by MarkJonas** [comment]
Docker Hub build failed: https://hub.docker.com/r/b3vis/borgmatic/builds/bmhwajby7avxezzwt2yhbf7/

But my local build succeeds.

@b3vis do you have an idea what is going on?

**Comment by b3vis** [comment]
Hey @MarkJonas I checked and it just says Unexpected Error with no log. My local build also completed and I kicked off a new build and it was successful so not sure!

**Pull request merged**
