### PR TITLE
Allow multiple borgmatic configuration files

### PR DESCRIPTION
**Pull request by toastie89**
Borgmatic allows mutliple configuration files:
https://github.com/witten/borgmatic#multiple-configuration-files

Removed `-c` parameter and added a volume for `/etc/borgmatic.d` to store the configuration instead.
Borgmatic searches by default for configuration files in this directory.

### CODE REVIEW

**Comment by b3vis** [comment]
Hi there,

Thanks for the PR, I was thinking if we should remove the /config volume but remembered that this is where crontab.txt lives so we can leave it there for now. I'll merge this in now.

Thanks,
b3vis

**Comment by toastie89** [comment]
Thanks for merging!

- Regarding the `crontab.txt` I would suggest to store it under root's home directory `/root/crontab.txt` rather than having another folder.
- Further I would suggest to have another volume for the config `/root/.config/borg`.
- To be consistent with the standard, instead of moving the cache I would suggest having a volume for `/root/.cache/borg` instead.

I'm currently preparing a `docker-compose.yml` and would submit a pull-request with updated volumes if you agree.

**Comment by b3vis** [comment]
Sounds good to me!

**Comment by toastie89** [comment]
Just created a pull request (sorry, created in two pieces by mistake #10  #11 ) with the `docker-compose.yml` and corresponding `.env`. Folder locations are not changed yet. I would put this change in another pull request as we'll need to touch several places.

**Pull request merged**
